# Generated by Django 6.0.4 on 2026-05-05 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temperature', models.IntegerField()),
                ('humidite', models.IntegerField()),
                ('pluie_mm', models.IntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('surface_ha', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('etat', models.CharField(choices=[('OK', 'OK'), ('Stress hydrique', 'Stress hydrique'), ('Maladie détectée', 'Maladie détectée'), ('Risque maladie', 'Risque maladie')], max_length=255)),
                ('commentaire', models.CharField(blank=True, max_length=255, null=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='agricole.parcelle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Blé', 'Blé'), ('Maïs', 'Maïs'), ('Orge', 'Orge'), ('Tournesol', 'Tournesol'), ('Colza', 'Colza')], max_length=255)),
                ('date_semis', models.DateField()),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='agricole.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('niveau', models.CharField(choices=[('1', 'Faible'), ('2', 'Moyen'), ('3', 'Élevé')], max_length=1)),
                ('est_lue', models.BooleanField(default=False)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='agricole.parcelle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
