# Generated by Django 6.0.4 on 2026-05-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='niveau',
            field=models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyen'), (3, 'Élevé')]),
        ),
    ]
