# Generated by Django 6.0.4 on 2026-05-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0002_alter_alerte_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('Stress hydrique', 'Stress hydrique'), ('Risque maladie', 'Risque maladie')], max_length=255)),
                ('temp_faible_min', models.FloatField(blank=True, null=True)),
                ('temp_faible_max', models.FloatField(blank=True, null=True)),
                ('temp_moyen_min', models.FloatField(blank=True, null=True)),
                ('temp_moyen_max', models.FloatField(blank=True, null=True)),
                ('temp_eleve_min', models.FloatField(blank=True, null=True)),
                ('temp_eleve_max', models.FloatField(blank=True, null=True)),
                ('humidite_faible_min', models.IntegerField(blank=True, null=True)),
                ('humidite_faible_max', models.IntegerField(blank=True, null=True)),
                ('humidite_moyen_min', models.IntegerField(blank=True, null=True)),
                ('humidite_moyen_max', models.IntegerField(blank=True, null=True)),
                ('humidite_eleve_min', models.IntegerField(blank=True, null=True)),
                ('humidite_eleve_max', models.IntegerField(blank=True, null=True)),
                ('pluie_faible_min', models.FloatField(blank=True, null=True)),
                ('pluie_faible_max', models.FloatField(blank=True, null=True)),
                ('pluie_moyen_min', models.FloatField(blank=True, null=True)),
                ('pluie_moyen_max', models.FloatField(blank=True, null=True)),
                ('pluie_eleve_min', models.FloatField(blank=True, null=True)),
                ('pluie_eleve_max', models.FloatField(blank=True, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_alertes', to='agricole.culture')),
            ],
            options={
                'ordering': ['culture', 'type_alerte'],
                'unique_together': {('culture', 'type_alerte')},
            },
        ),
    ]
