# Generated by Django 6.0.4 on 2026-05-07 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0003_reglealerte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Blé', 'Blé'), ('Maïs', 'Maïs'), ('Orge', 'Orge'), ('Tournesol', 'Tournesol'), ('Colza', 'Colza')], max_length=255, unique=True)),
                ('temp_stress_faible_min', models.FloatField(blank=True, null=True)),
                ('temp_stress_faible_max', models.FloatField(blank=True, null=True)),
                ('temp_stress_moyen_min', models.FloatField(blank=True, null=True)),
                ('temp_stress_moyen_max', models.FloatField(blank=True, null=True)),
                ('temp_stress_eleve_min', models.FloatField(blank=True, null=True)),
                ('temp_stress_eleve_max', models.FloatField(blank=True, null=True)),
                ('humidite_stress_faible_min', models.IntegerField(blank=True, null=True)),
                ('humidite_stress_faible_max', models.IntegerField(blank=True, null=True)),
                ('humidite_stress_moyen_min', models.IntegerField(blank=True, null=True)),
                ('humidite_stress_moyen_max', models.IntegerField(blank=True, null=True)),
                ('humidite_stress_eleve_min', models.IntegerField(blank=True, null=True)),
                ('humidite_stress_eleve_max', models.IntegerField(blank=True, null=True)),
                ('pluie_stress_faible_min', models.FloatField(blank=True, null=True)),
                ('pluie_stress_faible_max', models.FloatField(blank=True, null=True)),
                ('pluie_stress_moyen_min', models.FloatField(blank=True, null=True)),
                ('pluie_stress_moyen_max', models.FloatField(blank=True, null=True)),
                ('pluie_stress_eleve_min', models.FloatField(blank=True, null=True)),
                ('pluie_stress_eleve_max', models.FloatField(blank=True, null=True)),
                ('temp_maladie_faible_min', models.FloatField(blank=True, null=True)),
                ('temp_maladie_faible_max', models.FloatField(blank=True, null=True)),
                ('temp_maladie_moyen_min', models.FloatField(blank=True, null=True)),
                ('temp_maladie_moyen_max', models.FloatField(blank=True, null=True)),
                ('temp_maladie_eleve_min', models.FloatField(blank=True, null=True)),
                ('temp_maladie_eleve_max', models.FloatField(blank=True, null=True)),
                ('humidite_maladie_faible_min', models.IntegerField(blank=True, null=True)),
                ('humidite_maladie_faible_max', models.IntegerField(blank=True, null=True)),
                ('humidite_maladie_moyen_min', models.IntegerField(blank=True, null=True)),
                ('humidite_maladie_moyen_max', models.IntegerField(blank=True, null=True)),
                ('humidite_maladie_eleve_min', models.IntegerField(blank=True, null=True)),
                ('humidite_maladie_eleve_max', models.IntegerField(blank=True, null=True)),
                ('pluie_maladie_faible_min', models.FloatField(blank=True, null=True)),
                ('pluie_maladie_faible_max', models.FloatField(blank=True, null=True)),
                ('pluie_maladie_moyen_min', models.FloatField(blank=True, null=True)),
                ('pluie_maladie_moyen_max', models.FloatField(blank=True, null=True)),
                ('pluie_maladie_eleve_min', models.FloatField(blank=True, null=True)),
                ('pluie_maladie_eleve_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ['-date_semis']},
        ),
        migrations.RemoveField(
            model_name='culture',
            name='type',
        ),
        migrations.AddField(
            model_name='culture',
            name='plante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='agricole.plante'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RegleAlerte',
        ),
    ]
